[[plugins]]
package = "netlify-plugin-cache"

  [plugins.inputs]
  paths = [ "_site/img", ".cache" ]

[[redirects]]
from = "/thingstodo"
to = "/visit"
status = 301
force = true

[[redirects]]
from = "/thingstodo.html"
to = "/visit"
status = 301
force = true

[[redirects]]
from = "/danceprof"
to = "/danceprofessional"
status = 301
force = true

[[redirects]]
from = "/danceprof.html"
to = "/danceprofessional"
status = 301
force = true

[[redirects]]
from = "/showtime"
to = "/repertoire"
status = 301
force = true

[[redirects]]
from = "/showtime.html"
to = "/repertoire"
status = 301
force = true

[[redirects]]
from = "/danceaware"
to = "/popularising-the-arts/#danceaware"
status = 301
force = true

[[redirects]]
from = "/danceaware.html"
to = "/popularising-the-arts/#danceaware"
status = 301
force = true

[[redirects]]
from = "/villageoutreach"
to = "/village-outreach"
status = 301
force = true

[[redirects]]
from = "/villageoutreach.html"
to = "/village-outreach"
status = 301
force = true

[[redirects]]
from = "/supportingartists"
to = "/kula-artistes-residence"
status = 301
force = true

[[redirects]]
from = "/supportingartists.html"
to = "/kula-artistes-residence"
status = 301
force = true

[[redirects]]
from = "/popularisingarts"
to = "/popularising-the-arts"
status = 301
force = true

[[redirects]]
from = "/popularisingarts.html"
to = "/popularising-the-arts"
status = 301
force = true

[[redirects]]
from = "/popularisingarts#vasant"
to = "/popularising-the-arts/#vasantahabba"
status = 301
force = true

[[redirects]]
from = "/popularisingarts#ajji"
to = "/popularising-the-arts/#ajji"
status = 301
force = true

[[redirects]]
from = "/vision"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/vision.html"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/artists/protima/*"
to = "/protima"
status = 301
force = true

[[redirects]]
from = "/4artists/protima/*"
to = "/protima"
status = 301
force = true

[[redirects]]
from = "/artists/surupa/*"
to = "/surupa"
status = 301
force = true

[[redirects]]
from = "/4artists/surupa/*"
to = "/surupa"
status = 301
force = true

[[redirects]]
from = "/artists/bijayini/*"
to = "/bijayini"
status = 301
force = true

[[redirects]]
from = "/4artists/bijayini/*"
to = "/bijayini"
status = 301
force = true

[[redirects]]
from = "/artists/rising/*"
to = "/pavithra"
status = 301
force = true

[[redirects]]
from = "/4artists/rising/*"
to = "/pavithra"
status = 301
force = true

[[redirects]]
from = "/artists/ensemble/*"
to = "/ensemble"
status = 301
force = true

[[redirects]]
from = "/expression/bnatyam/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/6expression/bnatyam/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/expression/odissi/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/6expression/odissi/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/soul/gurukul/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/soul/dream/*"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/soul/future/*"
to = "/future"
status = 301
force = true

[[redirects]]
from = "/soul/philosophy/*"
to = "/about"
status = 301
force = true

[[redirects]]
from = "/passion/habba/*"
to = "/popularising-the-arts/#vasantahabba"
status = 301
force = true

[[redirects]]
from = "/passion/perform/*"
to = "/repertoire"
status = 301
force = true

[[redirects]]
from = "/reviews/*"
to = "/press"
status = 301
force = true

[[redirects]]
from = "/village/friends/*"
to = "/community"
status = 301
force = true

[[redirects]]
from = "/wisdom/apply/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/2wisdom/apply/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/wisdom/prog/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/2wisdom/prog/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/contact/*"
to = "/"
status = 301
force = true

[[redirects]]
from = "/lifeatng.html"
to = "/community"
status = 301
force = true

[[redirects]]
from = "/village/spaces/guest*"
to = "/kula-artistes-residence"
status = 301
force = true

[[redirects]]
from = "/village/spaces/*"
to = "/space"
status = 301
force = true

[[redirects]]
from = "/village/sponsors*"
to = "/support"
status = 301
force = true

[[redirects]]
from = "/wisdom/workshops/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/2wisdom/workshops/*"
to = "/gurukula"
status = 301
force = true

[[redirects]]
from = "/soul/future/"
to = "/future"
status = 301
force = true

[[redirects]]
from = "/space.*"
to = "/space"
status = 301
force = true

[[redirects]]
from = "/ngangels.html"
to = "/support"
status = 301
force = true

[[redirects]]
from = "/friendsofng.html"
to = "/support"
status = 301
force = true

[[redirects]]
from = "/expression/kathak/*"
to = "/gurukula"
status = 301
force = true
